/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import commons.report.pkg1.pkg8.pkg2.vreport;
import conexoes.ConexaoMySql;
import controller.ControllerCliente;
import controller.ControllerFornecedor;
import controller.ControllerPermissaousuario;
import controller.ControllerProdutos;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.ModelPermissaousuario;
import model.ModelSessaoUsuario;
import util.AguardeGerandoRelatorio;
import util.BLDatas;
import view.ViewAtivacao;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Vitor Aguiar desenvolvimento de Sistemas
 *
 */
public class ViewiPrincipal extends javax.swing.JFrame {
    
    String pNomeUsuario;
     public ResultSet rs;
    ConexaoMySql con = new ConexaoMySql();
 
   
 
  
    /**
     * Creates new form ViewPrincipal
     */
    public ViewiPrincipal() {
        
       setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        configurar();
        liberarModulos();
        
        URL caminhoIcone = getClass().getResource("/imagens/pay.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        
        con.conectar();
        con.executarSQL("select * from ativacao");
        try {
            con.resultSet.last();
           char[] data  = con.resultSet.getString("vencimento").toCharArray();
           
          jLabelLicenca.setText("O Sistema Expira em: "+data[0]+data[1]+"/"+data[2]+data[3]+"/"+data[4]+data[5]+data[6]+data[7]);
        } catch (SQLException ex) {
            Logger.getLogger(ViewiPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        uJPanelImagem1 = new componentes.UJPanelImagem();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel4 = new javax.swing.JPanel();
        btClientes = new javax.swing.JButton();
        btProdutos = new javax.swing.JButton();
        btFornecedores = new javax.swing.JButton();
        btUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btRegistrarVenda = new javax.swing.JButton();
        btOrcamento = new javax.swing.JButton();
        btPDV = new javax.swing.JButton();
        jbConsultaVendas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jlData = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelLicenca = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmArquivo = new javax.swing.JMenu();
        jmiSobre = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        mnuSair = new javax.swing.JMenuItem();
        jMenuAtivacao = new javax.swing.JMenuItem();
        jmCadastrar = new javax.swing.JMenu();
        jmiClientes = new javax.swing.JMenuItem();
        jmiProdutos = new javax.swing.JMenuItem();
        jmiFornecedor = new javax.swing.JMenuItem();
        jmiUsuario = new javax.swing.JMenuItem();
        miCidades = new javax.swing.JMenuItem();
        miEmpresa = new javax.swing.JMenuItem();
        miUnidadeMedida = new javax.swing.JMenuItem();
        miFormaPagamento = new javax.swing.JMenuItem();
        jmiCompras = new javax.swing.JMenuItem();
        jmVendas = new javax.swing.JMenu();
        jmiRegistrarVenda = new javax.swing.JMenuItem();
        jmiConsultarVenda = new javax.swing.JMenuItem();
        miOrcamento = new javax.swing.JMenuItem();
        miPDV = new javax.swing.JMenuItem();
        jmFinanceiro = new javax.swing.JMenu();
        jmiContasPagar = new javax.swing.JMenuItem();
        jmiContasReceber = new javax.swing.JMenuItem();
        miFluxoCaixa = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiRelClientes = new javax.swing.JMenuItem();
        jmiRelFornecedor = new javax.swing.JMenuItem();
        jmiRelProdutos = new javax.swing.JMenuItem();
        jmiRelatorioVendasPeriodo = new javax.swing.JMenuItem();
        jmiRelatorioVenda = new javax.swing.JMenuItem();
        jmiRelatorioContasPagar = new javax.swing.JMenuItem();
        miRelatorioContasReceber = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmAjuda = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("jMenu4");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DG SOFTWARE ERP  Pro 3.0");
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);

        uJPanelImagem1.setImagem(new java.io.File("C:\\BLVendasPdvMySQL\\src\\imagens\\software.jpg"));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu rápido", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N
        jToolBar1.setForeground(new java.awt.Color(102, 102, 102));
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/contact.png"))); // NOI18N
        btClientes.setText("Clientes");
        btClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btClientes.setEnabled(false);
        btClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btClientes.setMaximumSize(new java.awt.Dimension(200, 40));
        btClientes.setMinimumSize(new java.awt.Dimension(200, 40));
        btClientes.setPreferredSize(new java.awt.Dimension(200, 40));
        btClientes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClientesActionPerformed(evt);
            }
        });
        jPanel4.add(btClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 150, 130));

        btProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/open-box.png"))); // NOI18N
        btProdutos.setText("Produtos");
        btProdutos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btProdutos.setEnabled(false);
        btProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btProdutos.setMaximumSize(new java.awt.Dimension(200, 40));
        btProdutos.setMinimumSize(new java.awt.Dimension(200, 40));
        btProdutos.setPreferredSize(new java.awt.Dimension(200, 40));
        btProdutos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutosActionPerformed(evt);
            }
        });
        jPanel4.add(btProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 150, 130));

        btFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/manager.png"))); // NOI18N
        btFornecedores.setText("Fornecedor");
        btFornecedores.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btFornecedores.setEnabled(false);
        btFornecedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFornecedores.setMaximumSize(new java.awt.Dimension(200, 40));
        btFornecedores.setMinimumSize(new java.awt.Dimension(200, 40));
        btFornecedores.setPreferredSize(new java.awt.Dimension(200, 40));
        btFornecedores.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btFornecedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFornecedoresActionPerformed(evt);
            }
        });
        jPanel4.add(btFornecedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 150, 130));

        btUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/user.png"))); // NOI18N
        btUsuario.setText("Usuário");
        btUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btUsuario.setEnabled(false);
        btUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btUsuario.setMaximumSize(new java.awt.Dimension(200, 40));
        btUsuario.setMinimumSize(new java.awt.Dimension(200, 40));
        btUsuario.setPreferredSize(new java.awt.Dimension(200, 40));
        btUsuario.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioActionPerformed(evt);
            }
        });
        jPanel4.add(btUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 150, 130));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vendas");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        btRegistrarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/cart.png"))); // NOI18N
        btRegistrarVenda.setText("Registrrar venda");
        btRegistrarVenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btRegistrarVenda.setEnabled(false);
        btRegistrarVenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btRegistrarVenda.setMaximumSize(new java.awt.Dimension(200, 40));
        btRegistrarVenda.setMinimumSize(new java.awt.Dimension(200, 40));
        btRegistrarVenda.setPreferredSize(new java.awt.Dimension(200, 40));
        btRegistrarVenda.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btRegistrarVenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btRegistrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarVendaActionPerformed(evt);
            }
        });
        jPanel4.add(btRegistrarVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 150, 130));

        btOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/cart.png"))); // NOI18N
        btOrcamento.setText("Registrar Orçamento");
        btOrcamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btOrcamento.setEnabled(false);
        btOrcamento.setFocusable(false);
        btOrcamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btOrcamento.setMaximumSize(new java.awt.Dimension(200, 40));
        btOrcamento.setMinimumSize(new java.awt.Dimension(200, 40));
        btOrcamento.setPreferredSize(new java.awt.Dimension(200, 40));
        btOrcamento.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btOrcamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrcamentoActionPerformed(evt);
            }
        });
        jPanel4.add(btOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 150, 130));

        btPDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/cart.png"))); // NOI18N
        btPDV.setText("Venda em PDV");
        btPDV.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btPDV.setEnabled(false);
        btPDV.setFocusable(false);
        btPDV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPDV.setMaximumSize(new java.awt.Dimension(200, 40));
        btPDV.setMinimumSize(new java.awt.Dimension(200, 40));
        btPDV.setPreferredSize(new java.awt.Dimension(200, 40));
        btPDV.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btPDV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPDVActionPerformed(evt);
            }
        });
        jPanel4.add(btPDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 150, 130));

        jbConsultaVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/search.png"))); // NOI18N
        jbConsultaVendas.setText("Consultar vendas");
        jbConsultaVendas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbConsultaVendas.setEnabled(false);
        jbConsultaVendas.setFocusable(false);
        jbConsultaVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbConsultaVendas.setMaximumSize(new java.awt.Dimension(200, 40));
        jbConsultaVendas.setMinimumSize(new java.awt.Dimension(200, 40));
        jbConsultaVendas.setPreferredSize(new java.awt.Dimension(200, 40));
        jbConsultaVendas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbConsultaVendas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbConsultaVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultaVendasActionPerformed(evt);
            }
        });
        jPanel4.add(jbConsultaVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 150, 130));

        jToolBar1.add(jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alt+C = Clientes   -   Alt+P = Produtos   -   Alt+F = Fornecedor   -   Alt+V = Vendas  -   Alt+G = Contas Pagar   -    Alt+R = Contas a Receber   -  Orçamento =  ALt+O   -   Alt+D = PDV");
        jPanel2.add(jLabel6);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N
        jLabel3.setOpaque(true);

        javax.swing.GroupLayout uJPanelImagem1Layout = new javax.swing.GroupLayout(uJPanelImagem1);
        uJPanelImagem1.setLayout(uJPanelImagem1Layout);
        uJPanelImagem1Layout.setHorizontalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE))
        );
        uJPanelImagem1Layout.setVerticalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Logado como:");

        jlUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlUsuario.setText("usuaario");

        jlData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlData.setForeground(new java.awt.Color(255, 255, 255));
        jlData.setText("data");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data/Hora de login:");

        jLabelLicenca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelLicenca.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLicenca.setText("licença");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addComponent(jLabelLicenca, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlData, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jlData, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelLicenca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jmArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Folder.png"))); // NOI18N
        jmArquivo.setText("Arquivo");

        jmiSobre.setText("Sobre o Sistema...");
        jmiSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSobreActionPerformed(evt);
            }
        });
        jmArquivo.add(jmiSobre);
        jmArquivo.add(jSeparator1);

        mnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        jmArquivo.add(mnuSair);

        jMenuAtivacao.setText("Ativar Sistema");
        jMenuAtivacao.setEnabled(false);
        jMenuAtivacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAtivacaoActionPerformed(evt);
            }
        });
        jmArquivo.add(jMenuAtivacao);

        jMenuBar1.add(jmArquivo);

        jmCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Create.png"))); // NOI18N
        jmCadastrar.setText("Cadastros");

        jmiClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jmiClientes.setText("Clientes");
        jmiClientes.setEnabled(false);
        jmiClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClientesActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiClientes);

        jmiProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jmiProdutos.setText("Produtos");
        jmiProdutos.setEnabled(false);
        jmiProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProdutosActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiProdutos);

        jmiFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jmiFornecedor.setText("Fornecedores");
        jmiFornecedor.setEnabled(false);
        jmiFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFornecedorActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiFornecedor);

        jmiUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jmiUsuario.setText("Usuário");
        jmiUsuario.setEnabled(false);
        jmiUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUsuarioActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiUsuario);

        miCidades.setText("Cidades");
        miCidades.setEnabled(false);
        miCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCidadesActionPerformed(evt);
            }
        });
        jmCadastrar.add(miCidades);

        miEmpresa.setText("Empresa");
        miEmpresa.setEnabled(false);
        miEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEmpresaActionPerformed(evt);
            }
        });
        jmCadastrar.add(miEmpresa);

        miUnidadeMedida.setText("Unidade de Medida");
        miUnidadeMedida.setEnabled(false);
        miUnidadeMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUnidadeMedidaActionPerformed(evt);
            }
        });
        jmCadastrar.add(miUnidadeMedida);

        miFormaPagamento.setText("Forma de Pagamento");
        miFormaPagamento.setEnabled(false);
        miFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFormaPagamentoActionPerformed(evt);
            }
        });
        jmCadastrar.add(miFormaPagamento);

        jmiCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/New.png"))); // NOI18N
        jmiCompras.setText("Compras");
        jmiCompras.setEnabled(false);
        jmiCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiComprasActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiCompras);

        jMenuBar1.add(jmCadastrar);

        jmVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Shopping cart.png"))); // NOI18N
        jmVendas.setText("Vendas");

        jmiRegistrarVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        jmiRegistrarVenda.setText("Vendas");
        jmiRegistrarVenda.setEnabled(false);
        jmiRegistrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegistrarVendaActionPerformed(evt);
            }
        });
        jmVendas.add(jmiRegistrarVenda);

        jmiConsultarVenda.setText("Consultar vendas");
        jmiConsultarVenda.setEnabled(false);
        jmiConsultarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultarVendaActionPerformed(evt);
            }
        });
        jmVendas.add(jmiConsultarVenda);

        miOrcamento.setText("Orcamento");
        miOrcamento.setEnabled(false);
        miOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOrcamentoActionPerformed(evt);
            }
        });
        jmVendas.add(miOrcamento);

        miPDV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        miPDV.setText("Vendas em PDV");
        miPDV.setEnabled(false);
        miPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPDVActionPerformed(evt);
            }
        });
        jmVendas.add(miPDV);

        jMenuBar1.add(jmVendas);

        jmFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Dollar.png"))); // NOI18N
        jmFinanceiro.setText("Financeiro");

        jmiContasPagar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jmiContasPagar.setText("Conta a pagar");
        jmiContasPagar.setEnabled(false);
        jmiContasPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiContasPagarActionPerformed(evt);
            }
        });
        jmFinanceiro.add(jmiContasPagar);

        jmiContasReceber.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jmiContasReceber.setText("Contas a receber");
        jmiContasReceber.setEnabled(false);
        jmiContasReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiContasReceberActionPerformed(evt);
            }
        });
        jmFinanceiro.add(jmiContasReceber);

        miFluxoCaixa.setText("Fluxo de caixa");
        miFluxoCaixa.setEnabled(false);
        miFluxoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFluxoCaixaActionPerformed(evt);
            }
        });
        jmFinanceiro.add(miFluxoCaixa);

        jMenuBar1.add(jmFinanceiro);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Report.png"))); // NOI18N
        jMenu1.setText("Relatórios");

        jmiRelClientes.setText("Clientes");
        jmiRelClientes.setEnabled(false);
        jmiRelClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelClientes);

        jmiRelFornecedor.setText("Fornecedores");
        jmiRelFornecedor.setEnabled(false);
        jmiRelFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelFornecedor);

        jmiRelProdutos.setText("Produtos");
        jmiRelProdutos.setEnabled(false);
        jmiRelProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelProdutos);

        jmiRelatorioVendasPeriodo.setText("Vendas por peíodo");
        jmiRelatorioVendasPeriodo.setEnabled(false);
        jmiRelatorioVendasPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioVendasPeriodoActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelatorioVendasPeriodo);

        jmiRelatorioVenda.setText("Venda unitária");
        jmiRelatorioVenda.setEnabled(false);
        jmiRelatorioVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioVendaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelatorioVenda);

        jmiRelatorioContasPagar.setText("Relatório de contas a pagar");
        jmiRelatorioContasPagar.setEnabled(false);
        jmiRelatorioContasPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioContasPagarActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelatorioContasPagar);

        miRelatorioContasReceber.setText("Relatório de contas a receber");
        miRelatorioContasReceber.setEnabled(false);
        miRelatorioContasReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelatorioContasReceberActionPerformed(evt);
            }
        });
        jMenu1.add(miRelatorioContasReceber);

        jMenuItem1.setText("Código de barras");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jmAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Help.png"))); // NOI18N
        jmAjuda.setText("Ajuda");

        jMenuItem3.setText("Contato");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jmAjuda.add(jMenuItem3);

        jMenuBar1.add(jmAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1205, 838));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSobreActionPerformed
        JOptionPane.showMessageDialog(null, "DG SOFTWARE ERP 3.0/ Atualizado 2018");
    }//GEN-LAST:event_jmiSobreActionPerformed

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSairActionPerformed

    private void jmiClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClientesActionPerformed
        new ViewClientes().setVisible(true);
    }//GEN-LAST:event_jmiClientesActionPerformed

    private void jmiProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProdutosActionPerformed
        new ViewProduto().setVisible(true);
    }//GEN-LAST:event_jmiProdutosActionPerformed

    private void jmiFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFornecedorActionPerformed
        new ViewFornecedor().setVisible(true);
    }//GEN-LAST:event_jmiFornecedorActionPerformed

    private void jmiRegistrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegistrarVendaActionPerformed
        new ViewVenda().setVisible(true);
    }//GEN-LAST:event_jmiRegistrarVendaActionPerformed

    private void jmiConsultarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultarVendaActionPerformed
        ViewVenda venda = new ViewVenda();
        venda.setViewConsultarVendas();
        venda.setVisible(true);
    }//GEN-LAST:event_jmiConsultarVendaActionPerformed

    private void jmiRelClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelClientesActionPerformed
        final AguardeGerandoRelatorio carregando = new AguardeGerandoRelatorio();
        final ControllerCliente controllerCliente = new ControllerCliente();
        carregando.setVisible(true);
        Thread t = new Thread() {
            @Override
            public void run() {
                // imprimir clientes
                controllerCliente.gerarRelatorioCliente();
                carregando.dispose();
            }
        };
        t.start();
    }//GEN-LAST:event_jmiRelClientesActionPerformed

    private void jmiRelFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelFornecedorActionPerformed
        final AguardeGerandoRelatorio carregando = new AguardeGerandoRelatorio();
        final ControllerFornecedor controllerFornecedor = new ControllerFornecedor();
        carregando.setVisible(true);
        Thread t = new Thread() {
            @Override
            public void run() {
                // imrimir fornecedores
                controllerFornecedor.gerarRelatorioFornecedor();
                carregando.dispose();
            }
        };
        t.start();
    }//GEN-LAST:event_jmiRelFornecedorActionPerformed

    private void jmiRelProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelProdutosActionPerformed
        final AguardeGerandoRelatorio carregando = new AguardeGerandoRelatorio();
        final ControllerProdutos controllerProdutos = new ControllerProdutos();
        carregando.setVisible(true);
        Thread t = new Thread() {
            @Override
            public void run() {
                // imprimir produtos
                controllerProdutos.gerarRelatorioProdutos();
                carregando.dispose();
            }
        };
        t.start();
    }//GEN-LAST:event_jmiRelProdutosActionPerformed

    private void jmiUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUsuarioActionPerformed
        // TODO add your handling code here:
        new ViewUsuario().setVisible(true);
    }//GEN-LAST:event_jmiUsuarioActionPerformed

    private void btRegistrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarVendaActionPerformed
        new ViewVenda().setVisible(true);
    }//GEN-LAST:event_btRegistrarVendaActionPerformed

    private void btUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuarioActionPerformed
        // TODO add your handling code here:
        new ViewUsuario().setVisible(true);
    }//GEN-LAST:event_btUsuarioActionPerformed

    private void btFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFornecedoresActionPerformed
        new ViewFornecedor().setVisible(true);
    }//GEN-LAST:event_btFornecedoresActionPerformed

    private void btProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutosActionPerformed
        new ViewProduto().setVisible(true);
    }//GEN-LAST:event_btProdutosActionPerformed

    private void btClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientesActionPerformed
        new ViewClientes().setVisible(true);
    }//GEN-LAST:event_btClientesActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new ViewSobre(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jmiRelatorioVendasPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioVendasPeriodoActionPerformed
        // TODO add your handling code here:
        new ViewRelatorioVendas().setVisible(true);
    }//GEN-LAST:event_jmiRelatorioVendasPeriodoActionPerformed

    private void jmiRelatorioVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioVendaActionPerformed
        // TODO add your handling code here:
        new ViewImprimirPDV(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jmiRelatorioVendaActionPerformed

    private void jmiContasPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiContasPagarActionPerformed
        // TODO add your handling code here:
        new ViewContasPagar().setVisible(true);
    }//GEN-LAST:event_jmiContasPagarActionPerformed

    private void jmiContasReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiContasReceberActionPerformed
        // TODO add your handling code here:
        new ViewContasReceber().setVisible(true);
    }//GEN-LAST:event_jmiContasReceberActionPerformed

    private void jmiRelatorioContasPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioContasPagarActionPerformed
        // TODO add your handling code here:
        new ViewRelatoriosContasPagar().setVisible(true);
    }//GEN-LAST:event_jmiRelatorioContasPagarActionPerformed

    private void miCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCidadesActionPerformed
        // TODO add your handling code here:
        new ViewCidade().setVisible(true);
    }//GEN-LAST:event_miCidadesActionPerformed

    private void miEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEmpresaActionPerformed
        // TODO add your handling code here:
        new ViewEmpresa().setVisible(true);
    }//GEN-LAST:event_miEmpresaActionPerformed

    private void miUnidadeMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUnidadeMedidaActionPerformed
        // TODO add your handling code here:
        new ViewUnidadeMedia().setVisible(true);
    }//GEN-LAST:event_miUnidadeMedidaActionPerformed

    private void miFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFormaPagamentoActionPerformed
        // TODO add your handling code here:
        new ViewFormaPagamento().setVisible(true);
    }//GEN-LAST:event_miFormaPagamentoActionPerformed

    private void btOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrcamentoActionPerformed
        // TODO add your handling code here:
        new ViewOrcamento().setVisible(true);
    }//GEN-LAST:event_btOrcamentoActionPerformed

    private void miRelatorioContasReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorioContasReceberActionPerformed
        // TODO add your handling code here:
        new ViewRelatoriosContasReceber().setVisible(true);
    }//GEN-LAST:event_miRelatorioContasReceberActionPerformed

    private void btPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPDVActionPerformed
        // TODO add your handling code here:
        new ViewPdv().setVisible(true);
    }//GEN-LAST:event_btPDVActionPerformed

    private void miOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOrcamentoActionPerformed
        // TODO add your handling code here:
        new ViewOrcamento().setVisible(true);
    }//GEN-LAST:event_miOrcamentoActionPerformed

    private void miPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPDVActionPerformed
        // TODO add your handling code here:
        new ViewPdv().setVisible(true);
    }//GEN-LAST:event_miPDVActionPerformed

    private void miFluxoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFluxoCaixaActionPerformed
        // TODO add your handling code here:
        new ViewFluxoCaixa().setVisible(true);
    }//GEN-LAST:event_miFluxoCaixaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new ViewCodigobarras().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmiComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiComprasActionPerformed
        // TODO add your handling code here:
        new ViewComprasProdutos().setVisible(true);
    }//GEN-LAST:event_jmiComprasActionPerformed

    private void jbConsultaVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultaVendasActionPerformed
        ViewVenda venda = new ViewVenda();
        venda.setViewConsultarVendas();
        venda.setVisible(true);
    }//GEN-LAST:event_jbConsultaVendasActionPerformed

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
           BLDatas bLDatas = new BLDatas();
        jlData.setText(bLDatas.retornarDataHora());
        
        timer1.start();
    }//GEN-LAST:event_timer1OnTime

    private void jMenuAtivacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAtivacaoActionPerformed
     new ViewAtivacao().setVisible(true);
    }//GEN-LAST:event_jMenuAtivacaoActionPerformed

    public String retornarUsuarioLogado(){
        return new ModelSessaoUsuario().nome;
    }
       
    private void cria() {
        JButton bt = new JButton("Código fonte");
        bt.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new vreport().setVisible(true);
            }
        });
//        jMenuBar1.add(bt);
    }
    
    private void configurar(){
        pNomeUsuario = retornarUsuarioLogado();
        jlUsuario.setText(pNomeUsuario);
        BLDatas bLDatas = new BLDatas();
        jlData.setText(bLDatas.retornarDataHora());
        
      timer1.start();
        
        
    }
    
    private void liberarModulos() {
        ControllerPermissaousuario controllerPermissaousuario = new ControllerPermissaousuario();
        ArrayList<ModelPermissaousuario> listaModelPermissaousuarios = new ArrayList<>();
        listaModelPermissaousuarios = controllerPermissaousuario.getListaPermissaousuarioController(new ModelSessaoUsuario().codigo);cria();
        for (int i = 0; i < listaModelPermissaousuarios.size(); i++) {
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("cliente")) {
                btClientes.setEnabled(true);
                jmiRelClientes.setEnabled(true);
                jmiClientes.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("produto")) {
                btProdutos.setEnabled(true);
                jmiRelProdutos.setEnabled(true);
                jmiProdutos.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("compras")) {
                jmiCompras.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("fornecedor")) {
                btFornecedores.setEnabled(true);
                jmiFornecedor.setEnabled(true);
                jmiRelFornecedor.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("usuario")) {
                btUsuario.setEnabled(true);
                jmiUsuario.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("venda")) {
                btRegistrarVenda.setEnabled(true);
                jmiRegistrarVenda.setEnabled(true);
                jmiConsultarVenda.setEnabled(true);
                jmiRelatorioVenda.setEnabled(true);
                jbConsultaVendas.setEnabled(true);
                jmiRelatorioVendasPeriodo.setEnabled(true);
                btPDV.setEnabled(true);
                miPDV.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("pagar")) {
                jmiContasPagar.setEnabled(true);
                jmiRelatorioContasPagar.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("receber")) {
                jmiContasReceber.setEnabled(true);
                miRelatorioContasReceber.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("caixa")) {           
                jmiRelatorioContasPagar.setEnabled(true);
                miFluxoCaixa.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("empresa")) {           
                miEmpresa.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("fornecedor")) {           
                jmiFornecedor.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("cidade")) {           
                miCidades.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("unidade")) {           
                miUnidadeMedida.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("pagamento")) {           
                miFormaPagamento.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("orcamento")) {           
                miOrcamento.setEnabled(true);
                btOrcamento.setEnabled(true);
            }
            if(listaModelPermissaousuarios.get(i).getPermissao().equals("ativacao")){
            jMenuAtivacao.setEnabled(true); 
            
              
            }
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewiPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClientes;
    private javax.swing.JButton btFornecedores;
    private javax.swing.JButton btOrcamento;
    private javax.swing.JButton btPDV;
    private javax.swing.JButton btProdutos;
    private javax.swing.JButton btRegistrarVenda;
    private javax.swing.JButton btUsuario;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelLicenca;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuAtivacao;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbConsultaVendas;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JMenu jmAjuda;
    private javax.swing.JMenu jmArquivo;
    private javax.swing.JMenu jmCadastrar;
    private javax.swing.JMenu jmFinanceiro;
    private javax.swing.JMenu jmVendas;
    private javax.swing.JMenuItem jmiClientes;
    private javax.swing.JMenuItem jmiCompras;
    private javax.swing.JMenuItem jmiConsultarVenda;
    private javax.swing.JMenuItem jmiContasPagar;
    private javax.swing.JMenuItem jmiContasReceber;
    private javax.swing.JMenuItem jmiFornecedor;
    private javax.swing.JMenuItem jmiProdutos;
    private javax.swing.JMenuItem jmiRegistrarVenda;
    private javax.swing.JMenuItem jmiRelClientes;
    private javax.swing.JMenuItem jmiRelFornecedor;
    private javax.swing.JMenuItem jmiRelProdutos;
    private javax.swing.JMenuItem jmiRelatorioContasPagar;
    private javax.swing.JMenuItem jmiRelatorioVenda;
    private javax.swing.JMenuItem jmiRelatorioVendasPeriodo;
    private javax.swing.JMenuItem jmiSobre;
    private javax.swing.JMenuItem jmiUsuario;
    private javax.swing.JMenuItem miCidades;
    private javax.swing.JMenuItem miEmpresa;
    private javax.swing.JMenuItem miFluxoCaixa;
    private javax.swing.JMenuItem miFormaPagamento;
    private javax.swing.JMenuItem miOrcamento;
    private javax.swing.JMenuItem miPDV;
    private javax.swing.JMenuItem miRelatorioContasReceber;
    private javax.swing.JMenuItem miUnidadeMedida;
    private javax.swing.JMenuItem mnuSair;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    private componentes.UJPanelImagem uJPanelImagem1;
    // End of variables declaration//GEN-END:variables

    private void JButton() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
